### PR TITLE
Documentation

### LINKED ISSUE #9: Improve and update documentation
Describe all the commands in readme.md, adding contributors guidelines

### PR DESCRIPTION
**Pull request by arendruni**
- User commands
- Getting started
- Contributing section
- Skaffolder documentation (not finished)
- Fixed typos (Also fixed in code 2e24115)

### CODE REVIEW

**Comment by arendruni** [comment]
- Added License badge [GitHub](https://github.com/skaffolder/skaffolder-cli/blob/master/LICENSE)

**Review by lucarducci — CHANGES_REQUESTED** [review]
- Add registration link
- Improve explanation -o option
- Split categories create and manage project
- Generators commands
- Add table contents
- Add gif getting started

**Comment by arendruni** [comment]
- [x] Add registration link
- [x] Improve explanation -o option
- [x] Split categories create and manage project
- [x] Generators commands
- [x] Add table contents
- [x] Add gif getting started

Plus:
- Resized Skaffolder logo
- HTML badges

**Comment by arendruni** [comment]
Added list templates command (#33)

**Pull request merged**
